version: '2'
services:
    zreporting-app:
        image: zreporting
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://zreporting-mariadb:3306/zreporting
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    zreporting-mariadb:
        extends:
            file: mariadb.yml
            service: zreporting-mariadb
